import {
  Bot,
  Calendar,
  CircleDollarSign,
  Cpu,
  Droplets,
  Home,
  LandPlot,
  Settings,
  Wheat,
  Truck,
  Package,
  Users,
  BarChart3,
  Map,
  MessageSquare,
} from "lucide-react"
import type {
  AlertData,
  Company,
  KpiCardData,
  NavItem,
  Vehicle,
  BiblicalVerse,
  Task,
  WeatherData,
  InventoryItem,
  FinancialData,
  Notification,
} from "./types"

export const navItems: NavItem[] = [
  { title: "Panel Principal", href: "/", icon: Home },
  { title: "Ganado", href: "/livestock", icon: Bot, badge: 3 },
  { title: "Cultivos", href: "/crops", icon: Wheat },
  { title: "IoT & Sensores", href: "/iot", icon: Cpu, badge: 12 },
  { title: "Flota", href: "/fleet", icon: Truck, badge: 2 },
  { title: "Inventario", href: "/inventory", icon: Package, badge: 5 },
  { title: "Finanzas", href: "/finance", icon: CircleDollarSign },
  { title: "Tareas", href: "/tasks", icon: Calendar, badge: 8 },
  { title: "Equipo", href: "/team", icon: Users },
  { title: "Reportes", href: "/reports", icon: BarChart3 },
  { title: "Mapa", href: "/map", icon: Map },
  { title: "Chat", href: "/chat", icon: MessageSquare, badge: 4 },
  { title: "Configuración", href: "/settings", icon: Settings },
]

export const kpiData: KpiCardData[] = [
  {
    title: "Total de Ganado",
    value: "1,250",
    change: "+2.5%",
    changeType: "increase",
    description: "desde el mes pasado",
    icon: Bot,
    trend: [1200, 1210, 1225, 1240, 1250],
    target: "1,300",
  },
  {
    title: "Hectáreas Activas",
    value: "8,420 ha",
    change: "+120 ha",
    changeType: "increase",
    description: "nuevos pastizales añadidos",
    icon: LandPlot,
    trend: [8200, 8250, 8300, 8380, 8420],
    target: "8,500 ha",
  },
  {
    title: "Efectivo Disponible",
    value: "$258.4k",
    change: "-8.1%",
    changeType: "decrease",
    description: "desde el mes pasado",
    icon: CircleDollarSign,
    trend: [280, 275, 270, 265, 258],
    target: "$300k",
  },
  {
    title: "Eficiencia Operativa",
    value: "94.2%",
    change: "+3.1%",
    changeType: "increase",
    description: "vs promedio mensual",
    icon: Droplets,
    trend: [89, 91, 92, 93, 94],
    target: "95%",
  },
]

export const alerts: AlertData[] = [
  {
    id: "alert-1",
    title: "Cerca Caída en Potrero #14",
    description: "El sensor G-45 reporta una caída de voltaje. Posible rotura de cerca eléctrica.",
    timestamp: "hace 2m",
    type: "alert",
    read: false,
    priority: "critical",
    category: "Infraestructura",
    actionRequired: true,
  },
  {
    id: "alert-2",
    title: "Mantenimiento de Tractor Vencido",
    description: "El vehículo #3 requiere servicio de 500 horas. Programar mantenimiento inmediatamente.",
    timestamp: "hace 1h",
    type: "warn",
    read: false,
    priority: "high",
    category: "Flota",
    actionRequired: true,
  },
  {
    id: "alert-3",
    title: "Batería Baja: Collar #822",
    description: "Batería del collar al 15%. Reemplazar en las próximas 24 horas.",
    timestamp: "hace 3h",
    type: "warn",
    read: true,
    priority: "medium",
    category: "Ganado",
    actionRequired: false,
  },
  {
    id: "alert-4",
    title: "Alerta Climática: Granizo",
    description: "Granizo severo pronosticado para las 4:00 PM. Proteger cultivos vulnerables.",
    timestamp: "hace 6h",
    type: "alert",
    read: true,
    priority: "high",
    category: "Clima",
    actionRequired: true,
  },
  {
    id: "alert-5",
    title: "Stock Bajo: Fertilizante NPK",
    description: "Quedan solo 2 sacos de fertilizante NPK. Reabastecer antes del próximo ciclo.",
    timestamp: "hace 8h",
    type: "warn",
    read: false,
    priority: "medium",
    category: "Inventario",
    actionRequired: false,
  },
]

export const companies: Company[] = [
  { id: "acme-farms", name: "Hacienda San José", logo: "/placeholder.svg?width=32&height=32" },
  { id: "pioneer-agri", name: "Agropecuaria El Progreso", logo: "/placeholder.svg?width=32&height=32" },
  { id: "greenfield-est", name: "Finca Verde Esperanza", logo: "/placeholder.svg?width=32&height=32" },
]

export const vehicles: Vehicle[] = [
  {
    id: "v001",
    name: "Tractor John Deere 6120M",
    type: "tractor",
    status: "active",
    location: "Potrero Norte",
    coordinates: { lat: -34.6037, lng: -58.3816 },
    fuelLevel: 85,
    lastMaintenance: "2024-01-15",
    nextMaintenance: "2024-02-15",
    hoursWorked: 1247,
    maxHours: 1500,
    driver: "Carlos Mendoza",
    issues: [],
    efficiency: 92,
    costPerHour: 45,
  },
  {
    id: "v002",
    name: "Cosechadora Case IH 8250",
    type: "harvester",
    status: "maintenance",
    location: "Taller Principal",
    coordinates: { lat: -34.6047, lng: -58.3826 },
    fuelLevel: 45,
    lastMaintenance: "2024-01-20",
    nextMaintenance: "2024-02-20",
    hoursWorked: 892,
    maxHours: 1000,
    driver: "Ana García",
    issues: ["Filtro de aire obstruido", "Revisión de cadenas"],
    efficiency: 78,
    costPerHour: 85,
  },
  {
    id: "v003",
    name: "Camión Ford F-350",
    type: "truck",
    status: "active",
    location: "Almacén Central",
    coordinates: { lat: -34.6057, lng: -58.3836 },
    fuelLevel: 92,
    lastMaintenance: "2024-01-10",
    nextMaintenance: "2024-03-10",
    hoursWorked: 567,
    maxHours: 800,
    driver: "Miguel Torres",
    issues: [],
    efficiency: 88,
    costPerHour: 35,
  },
  {
    id: "v004",
    name: "Pulverizadora Apache AS1250",
    type: "sprayer",
    status: "inactive",
    location: "Depósito Sur",
    coordinates: { lat: -34.6067, lng: -58.3846 },
    fuelLevel: 23,
    lastMaintenance: "2024-01-05",
    nextMaintenance: "2024-02-05",
    hoursWorked: 234,
    maxHours: 500,
    driver: "Luis Rodríguez",
    issues: ["Mantenimiento programado pendiente"],
    efficiency: 85,
    costPerHour: 55,
  },
]

export const tasks: Task[] = [
  {
    id: "t001",
    title: "Vacunación Ganado Sector A",
    description: "Aplicar vacuna contra fiebre aftosa a 150 cabezas de ganado",
    priority: "urgent",
    status: "pending",
    assignedTo: "Dr. Roberto Silva",
    dueDate: "2024-02-01",
    category: "Sanidad Animal",
    location: "Potrero A",
    estimatedHours: 4,
  },
  {
    id: "t002",
    title: "Reparar Cerca Eléctrica",
    description: "Reparar cerca caída en potrero #14 reportada por sensor G-45",
    priority: "high",
    status: "in-progress",
    assignedTo: "Carlos Mendoza",
    dueDate: "2024-01-30",
    category: "Mantenimiento",
    location: "Potrero #14",
    estimatedHours: 2,
  },
  {
    id: "t003",
    title: "Siembra de Maíz",
    description: "Preparar y sembrar 50 hectáreas de maíz en el sector norte",
    priority: "medium",
    status: "pending",
    assignedTo: "Ana García",
    dueDate: "2024-02-15",
    category: "Agricultura",
    location: "Sector Norte",
    estimatedHours: 16,
  },
  {
    id: "t004",
    title: "Mantenimiento Tractor #3",
    description: "Servicio de 500 horas para tractor John Deere",
    priority: "high",
    status: "overdue",
    assignedTo: "Miguel Torres",
    dueDate: "2024-01-25",
    category: "Flota",
    location: "Taller",
    estimatedHours: 6,
  },
]

export const weatherData: WeatherData = {
  temperature: 24,
  condition: "Parcialmente Nublado",
  humidity: 68,
  windSpeed: 12,
  windDirection: "NE",
  visibility: 8,
  uvIndex: 6,
  pressure: 1013,
  forecast: [
    { day: "Hoy", high: 26, low: 18, condition: "Parcialmente Nublado", precipitation: 10 },
    { day: "Mañana", high: 28, low: 20, condition: "Soleado", precipitation: 0 },
    { day: "Miércoles", high: 25, low: 17, condition: "Lluvia", precipitation: 80 },
    { day: "Jueves", high: 23, low: 15, condition: "Nublado", precipitation: 30 },
    { day: "Viernes", high: 27, low: 19, condition: "Soleado", precipitation: 5 },
  ],
}

export const inventoryItems: InventoryItem[] = [
  {
    id: "inv001",
    name: "Fertilizante NPK 20-20-20",
    category: "Fertilizantes",
    quantity: 2,
    unit: "sacos",
    minStock: 5,
    maxStock: 20,
    cost: 45.5,
    supplier: "AgroInsumos SA",
    lastRestocked: "2024-01-15",
    location: "Almacén A",
  },
  {
    id: "inv002",
    name: "Semilla de Maíz Híbrido",
    category: "Semillas",
    quantity: 150,
    unit: "kg",
    minStock: 100,
    maxStock: 500,
    cost: 12.3,
    supplier: "Semillas Premium",
    lastRestocked: "2024-01-20",
    location: "Cámara Fría",
  },
  {
    id: "inv003",
    name: "Herbicida Glifosato",
    category: "Agroquímicos",
    quantity: 8,
    unit: "litros",
    minStock: 10,
    maxStock: 50,
    cost: 28.75,
    supplier: "QuímicaAgro",
    lastRestocked: "2024-01-10",
    location: "Depósito Químicos",
    expiryDate: "2025-06-30",
  },
]

export const financialData: FinancialData = {
  totalRevenue: 485000,
  totalExpenses: 320000,
  netProfit: 165000,
  cashFlow: 258400,
  monthlyData: [
    { month: "Ene", revenue: 45000, expenses: 32000, profit: 13000 },
    { month: "Feb", revenue: 52000, expenses: 35000, profit: 17000 },
    { month: "Mar", revenue: 48000, expenses: 31000, profit: 17000 },
    { month: "Abr", revenue: 55000, expenses: 38000, profit: 17000 },
    { month: "May", revenue: 62000, expenses: 42000, profit: 20000 },
    { month: "Jun", revenue: 58000, expenses: 39000, profit: 19000 },
  ],
}

export const notifications: Notification[] = [
  {
    id: "n001",
    title: "Tarea Completada",
    message: "La vacunación del sector B ha sido completada exitosamente",
    type: "success",
    timestamp: "hace 5m",
    read: false,
    actionUrl: "/tasks",
    actionText: "Ver Tareas",
  },
  {
    id: "n002",
    title: "Alerta de Stock",
    message: "El fertilizante NPK está por debajo del stock mínimo",
    type: "warning",
    timestamp: "hace 15m",
    read: false,
    actionUrl: "/inventory",
    actionText: "Ver Inventario",
  },
  {
    id: "n003",
    title: "Nuevo Mensaje",
    message: "Carlos Mendoza envió un reporte de campo",
    type: "info",
    timestamp: "hace 30m",
    read: true,
    actionUrl: "/chat",
    actionText: "Ver Chat",
  },
]

export const biblicalVerses: BiblicalVerse[] = [
  {
    text: "Todo tiene su tiempo, y todo lo que se quiere debajo del cielo tiene su hora.",
    reference: "Eclesiastés 3:1",
  },
  {
    text: "El que labra su tierra se saciará de pan; mas el que sigue a los ociosos se llenará de pobreza.",
    reference: "Proverbios 28:19",
  },
  {
    text: "Mientras la tierra permanezca, no cesarán la sementera y la siega, el frío y el calor, el verano y el invierno, y el día y la noche.",
    reference: "Génesis 8:22",
  },
  {
    text: "Mirad las aves del cielo, que no siembran, ni siegan, ni recogen en graneros; y vuestro Padre celestial las alimenta.",
    reference: "Mateo 6:26",
  },
  {
    text: "El perezoso no ara a causa del invierno; pedirá, pues, en la siega, y no hallará.",
    reference: "Proverbios 20:4",
  },
]
