import {
  Bot,
  Calendar,
  CircleDollarSign,
  Cpu,
  Droplets,
  Home,
  LandPlot,
  Settings,
  Wheat,
  Truck,
  Package,
  Users,
  BarChart3,
  Map,
  MessageSquare,
  Tractor,
  Thermometer,
  AlertTriangle,
  Warehouse,
  Waves,
  TrendingUp,
} from "lucide-react"
import type {
  AlertData,
  Company,
  KpiCardData,
  NavItem,
  Vehicle,
  BiblicalVerse,
  Task,
  WeatherData,
  InventoryItem,
  FinancialData,
  Notification,
  MapLayer,
  MapZone,
  MapMarker,
  WeatherStation,
} from "./types"

export const navItems: NavItem[] = [
  { title: "Panel Principal", href: "/", icon: Home },
  { title: "Ganado", href: "/ganado", icon: Bot, badge: 3 },
  { title: "Cultivos", href: "/cultivos", icon: Wheat },
  { title: "IoT y Sensores", href: "/iot", icon: Cpu, badge: 12 },
  { title: "Flota", href: "/fleet", icon: Truck, badge: 2 },
  { title: "Inventario", href: "/inventory", icon: Package, badge: 5 },
  { title: "Finanzas", href: "/finance", icon: CircleDollarSign },
  { title: "Mercado", href: "/mercado", icon: TrendingUp },
  { title: "Tareas", href: "/tasks", icon: Calendar, badge: 8 },
  { title: "Equipo", href: "/team", icon: Users },
  { title: "Reportes", href: "/reports", icon: BarChart3 },
  { title: "Mapa", href: "/map", icon: Map },
  { title: "Chat", href: "/chat", icon: MessageSquare, badge: 4 },
  { title: "Configuración", href: "/settings", icon: Settings },
]

export const kpiData: KpiCardData[] = [
  {
    title: "Total de Ganado",
    value: "1,250",
    change: "+2.5%",
    changeType: "increase",
    description: "desde el mes pasado",
    icon: Bot,
    trend: [1200, 1210, 1225, 1240, 1250],
    target: "1,300",
  },
  {
    title: "Hectáreas Activas",
    value: "8,420 ha",
    change: "+120 ha",
    changeType: "increase",
    description: "nuevos pastizales añadidos",
    icon: LandPlot,
    trend: [8200, 8250, 8300, 8380, 8420],
    target: "8,500 ha",
  },
  {
    title: "Efectivo Disponible",
    value: "$258.4k",
    change: "-8.1%",
    changeType: "decrease",
    description: "desde el mes pasado",
    icon: CircleDollarSign,
    trend: [280, 275, 270, 265, 258],
    target: "$300k",
  },
  {
    title: "Eficiencia Operativa",
    value: "94.2%",
    change: "+3.1%",
    changeType: "increase",
    description: "vs promedio mensual",
    icon: Droplets,
    trend: [89, 91, 92, 93, 94],
    target: "95%",
  },
]

export const alerts: AlertData[] = [
  {
    id: "alert-1",
    title: "Cerca Caída en Potrero #14",
    description: "El sensor G-45 reporta una caída de voltaje. Posible rotura de cerca eléctrica.",
    timestamp: "hace 2m",
    type: "alert",
    read: false,
    priority: "critical",
    category: "Infraestructura",
    actionRequired: true,
  },
  {
    id: "alert-2",
    title: "Mantenimiento de Tractor Vencido",
    description: "El vehículo #3 requiere servicio de 500 horas. Programar mantenimiento inmediatamente.",
    timestamp: "hace 1h",
    type: "warn",
    read: false,
    priority: "high",
    category: "Flota",
    actionRequired: true,
  },
  {
    id: "alert-3",
    title: "Batería Baja: Collar #822",
    description: "Batería del collar al 15%. Reemplazar en las próximas 24 horas.",
    timestamp: "hace 3h",
    type: "warn",
    read: true,
    priority: "medium",
    category: "Ganado",
    actionRequired: false,
  },
  {
    id: "alert-4",
    title: "Alerta Climática: Granizo",
    description: "Granizo severo pronosticado para las 4:00 PM. Proteger cultivos vulnerables.",
    timestamp: "hace 6h",
    type: "alert",
    read: true,
    priority: "high",
    category: "Clima",
    actionRequired: true,
  },
  {
    id: "alert-5",
    title: "Stock Bajo: Fertilizante NPK",
    description: "Quedan solo 2 sacos de fertilizante NPK. Reabastecer antes del próximo ciclo.",
    timestamp: "hace 8h",
    type: "warn",
    read: false,
    priority: "medium",
    category: "Inventario",
    actionRequired: false,
  },
]

export const companies: Company[] = [
  { id: "acme-farms", name: "Hacienda San José", logo: "/placeholder.svg?width=32&height=32" },
  { id: "pioneer-agri", name: "Agropecuaria El Progreso", logo: "/placeholder.svg?width=32&height=32" },
  { id: "greenfield-est", name: "Finca Verde Esperanza", logo: "/placeholder.svg?width=32&height=32" },
]

export const vehicles: Vehicle[] = [
  {
    id: "v001",
    name: "Tractor John Deere 6120M",
    type: "tractor",
    status: "active",
    location: "Potrero Norte",
    coordinates: { lat: -34.6037, lng: -58.3816 },
    fuelLevel: 85,
    lastMaintenance: "2024-01-15",
    nextMaintenance: "2024-02-15",
    hoursWorked: 1247,
    maxHours: 1500,
    driver: "Carlos Mendoza",
    issues: [],
    efficiency: 92,
    costPerHour: 45,
  },
  {
    id: "v002",
    name: "Cosechadora Case IH 8250",
    type: "harvester",
    status: "maintenance",
    location: "Taller Principal",
    coordinates: { lat: -34.6047, lng: -58.3826 },
    fuelLevel: 45,
    lastMaintenance: "2024-01-20",
    nextMaintenance: "2024-02-20",
    hoursWorked: 892,
    maxHours: 1000,
    driver: "Ana García",
    issues: ["Filtro de aire obstruido", "Revisión de cadenas"],
    efficiency: 78,
    costPerHour: 85,
  },
  {
    id: "v003",
    name: "Camión Ford F-350",
    type: "truck",
    status: "active",
    location: "Almacén Central",
    coordinates: { lat: -34.6057, lng: -58.3836 },
    fuelLevel: 92,
    lastMaintenance: "2024-01-10",
    nextMaintenance: "2024-03-10",
    hoursWorked: 567,
    maxHours: 800,
    driver: "Miguel Torres",
    issues: [],
    efficiency: 88,
    costPerHour: 35,
  },
  {
    id: "v004",
    name: "Pulverizadora Apache AS1250",
    type: "sprayer",
    status: "inactive",
    location: "Depósito Sur",
    coordinates: { lat: -34.6067, lng: -58.3846 },
    fuelLevel: 23,
    lastMaintenance: "2024-01-05",
    nextMaintenance: "2024-02-05",
    hoursWorked: 234,
    maxHours: 500,
    driver: "Luis Rodríguez",
    issues: ["Mantenimiento programado pendiente"],
    efficiency: 85,
    costPerHour: 55,
  },
]

export const tasks: Task[] = [
  {
    id: "t001",
    title: "Vacunación Ganado Sector A",
    description: "Aplicar vacuna contra fiebre aftosa a 150 cabezas de ganado",
    priority: "urgent",
    status: "pending",
    assignedTo: "Dr. Roberto Silva",
    dueDate: "2024-02-01",
    category: "Sanidad Animal",
    location: "Potrero A",
    estimatedHours: 4,
  },
  {
    id: "t002",
    title: "Reparar Cerca Eléctrica",
    description: "Reparar cerca caída en potrero #14 reportada por sensor G-45",
    priority: "high",
    status: "in-progress",
    assignedTo: "Carlos Mendoza",
    dueDate: "2024-01-30",
    category: "Mantenimiento",
    location: "Potrero #14",
    estimatedHours: 2,
  },
  {
    id: "t003",
    title: "Siembra de Maíz",
    description: "Preparar y sembrar 50 hectáreas de maíz en el sector norte",
    priority: "medium",
    status: "pending",
    assignedTo: "Ana García",
    dueDate: "2024-02-15",
    category: "Agricultura",
    location: "Sector Norte",
    estimatedHours: 16,
  },
  {
    id: "t004",
    title: "Mantenimiento Tractor #3",
    description: "Servicio de 500 horas para tractor John Deere",
    priority: "high",
    status: "overdue",
    assignedTo: "Miguel Torres",
    dueDate: "2024-01-25",
    category: "Flota",
    location: "Taller",
    estimatedHours: 6,
  },
]

export const weatherData: WeatherData = {
  temperature: 24,
  condition: "Parcialmente Nublado",
  humidity: 68,
  windSpeed: 12,
  windDirection: "NE",
  visibility: 8,
  uvIndex: 6,
  pressure: 1013,
  forecast: [
    { day: "Hoy", high: 26, low: 18, condition: "Parcialmente Nublado", precipitation: 10 },
    { day: "Mañana", high: 28, low: 20, condition: "Soleado", precipitation: 0 },
    { day: "Miércoles", high: 25, low: 17, condition: "Lluvia", precipitation: 80 },
    { day: "Jueves", high: 23, low: 15, condition: "Nublado", precipitation: 30 },
    { day: "Viernes", high: 27, low: 19, condition: "Soleado", precipitation: 5 },
  ],
}

export const inventoryItems: InventoryItem[] = [
  {
    id: "inv001",
    name: "Fertilizante NPK 20-20-20",
    category: "Fertilizantes",
    quantity: 2,
    unit: "sacos",
    minStock: 5,
    maxStock: 20,
    cost: 45.5,
    supplier: "AgroInsumos SA",
    lastRestocked: "2024-01-15",
    location: "Almacén A",
  },
  {
    id: "inv002",
    name: "Semilla de Maíz Híbrido",
    category: "Semillas",
    quantity: 150,
    unit: "kg",
    minStock: 100,
    maxStock: 500,
    cost: 12.3,
    supplier: "Semillas Premium",
    lastRestocked: "2024-01-20",
    location: "Cámara Fría",
  },
  {
    id: "inv003",
    name: "Herbicida Glifosato",
    category: "Agroquímicos",
    quantity: 8,
    unit: "litros",
    minStock: 10,
    maxStock: 50,
    cost: 28.75,
    supplier: "QuímicaAgro",
    lastRestocked: "2024-01-10",
    location: "Depósito Químicos",
    expiryDate: "2025-06-30",
  },
  {
    id: "inv004",
    name: "Suplemento Alimenticio Ganado",
    category: "Alimentos",
    quantity: 45,
    unit: "sacos",
    minStock: 20,
    maxStock: 100,
    cost: 35.0,
    supplier: "NutriGanado Co",
    lastRestocked: "2024-01-25",
    location: "Almacén Alimentos",
  },
  {
    id: "inv005",
    name: "Antibióticos Veterinarios",
    category: "Veterinaria",
    quantity: 12,
    unit: "viales",
    minStock: 15,
    maxStock: 50,
    cost: 85.0,
    supplier: "VetMed Solutions",
    lastRestocked: "2024-01-18",
    location: "Botiquín Veterinario",
    expiryDate: "2025-12-31",
  },
  {
    id: "inv006",
    name: "Aceite Motor Tractor",
    category: "Mantenimiento",
    quantity: 6,
    unit: "galones",
    minStock: 8,
    maxStock: 25,
    cost: 42.0,
    supplier: "AceitesMáquina Pro",
    lastRestocked: "2024-01-12",
    location: "Taller",
  },
  {
    id: "inv007",
    name: "Tuberías de Riego",
    category: "Infraestructura",
    quantity: 25,
    unit: "metros",
    minStock: 50,
    maxStock: 200,
    cost: 15.5,
    supplier: "RiegoTech",
    lastRestocked: "2024-01-08",
    location: "Patio de Equipos",
  },
  {
    id: "inv008",
    name: "Bloques de Sal Mineral",
    category: "Alimentos",
    quantity: 18,
    unit: "bloques",
    minStock: 10,
    maxStock: 40,
    cost: 22.0,
    supplier: "Minerales Ganado Inc",
    lastRestocked: "2024-01-22",
    location: "Almacén Alimentos",
  },
]

export const financialData: FinancialData = {
  totalRevenue: 485000,
  totalExpenses: 320000,
  netProfit: 165000,
  cashFlow: 258400,
  monthlyData: [
    { month: "Ene", revenue: 45000, expenses: 32000, profit: 13000 },
    { month: "Feb", revenue: 52000, expenses: 35000, profit: 17000 },
    { month: "Mar", revenue: 48000, expenses: 31000, profit: 17000 },
    { month: "Abr", revenue: 55000, expenses: 38000, profit: 17000 },
    { month: "May", revenue: 62000, expenses: 42000, profit: 20000 },
    { month: "Jun", revenue: 58000, expenses: 39000, profit: 19000 },
  ],
}

export const notifications: Notification[] = [
  {
    id: "n001",
    title: "Tarea Completada",
    message: "La vacunación del sector B ha sido completada exitosamente",
    type: "success",
    timestamp: "hace 5m",
    read: false,
    actionUrl: "/tasks",
    actionText: "Ver Tareas",
  },
  {
    id: "n002",
    title: "Alerta de Stock",
    message: "El fertilizante NPK está por debajo del stock mínimo",
    type: "warning",
    timestamp: "hace 15m",
    read: false,
    actionUrl: "/inventory",
    actionText: "Ver Inventario",
  },
  {
    id: "n003",
    title: "Nuevo Mensaje",
    message: "Carlos Mendoza envió un reporte de campo",
    type: "info",
    timestamp: "hace 30m",
    read: true,
    actionUrl: "/chat",
    actionText: "Ver Chat",
  },
]

export const biblicalVerses: BiblicalVerse[] = [
  {
    text: "Todo tiene su tiempo, y todo lo que se quiere debajo del cielo tiene su hora.",
    reference: "Eclesiastés 3:1",
  },
  {
    text: "El que labra su tierra se saciará de pan; mas el que sigue a los ociosos se llenará de pobreza.",
    reference: "Proverbios 28:19",
  },
  {
    text: "Mientras la tierra permanezca, no cesarán la sementera y la siega, el frío y el calor, el verano y el invierno, y el día y la noche.",
    reference: "Génesis 8:22",
  },
  {
    text: "Mirad las aves del cielo, que no siembran, ni siegan, ni recogen en graneros; y vuestro Padre celestial las alimenta.",
    reference: "Mateo 6:26",
  },
  {
    text: "El perezoso no ara a causa del invierno; pedirá, pues, en la siega, y no hallará.",
    reference: "Proverbios 20:4",
  },
]

export const mapLayers: MapLayer[] = [
  { id: "potreros", name: "Potreros", visible: true, color: "#22c55e", icon: LandPlot },
  { id: "cultivos", name: "Cultivos", visible: true, color: "#eab308", icon: Wheat },
  { id: "vehiculos", name: "Vehículos", visible: true, color: "#3b82f6", icon: Truck },
  { id: "sensores", name: "Sensores IoT", visible: true, color: "#8b5cf6", icon: Cpu },
  { id: "infraestructura", name: "Infraestructura", visible: true, color: "#ef4444", icon: Home },
  { id: "agua", name: "Fuentes de Agua", visible: true, color: "#06b6d4", icon: Droplets },
  { id: "alertas", name: "Alertas", visible: true, color: "#f97316", icon: AlertTriangle },
]

export const mapZones: MapZone[] = [
  {
    id: "potrero-1",
    name: "Potrero Norte",
    type: "potrero",
    coordinates: [
      { lat: -34.602, lng: -58.38 },
      { lat: -34.602, lng: -58.375 },
      { lat: -34.598, lng: -58.375 },
      { lat: -34.598, lng: -58.38 },
    ],
    center: { lat: -34.6, lng: -58.3775 },
    area: 45.5,
    status: "bueno",
    details: {
      ganado: 85,
      estado: "Pastoreo rotativo",
      ultimaInspeccion: "2024-01-28",
      responsable: "Carlos Mendoza",
    },
  },
  {
    id: "potrero-2",
    name: "Potrero Sur",
    type: "potrero",
    coordinates: [
      { lat: -34.608, lng: -58.38 },
      { lat: -34.608, lng: -58.375 },
      { lat: -34.604, lng: -58.375 },
      { lat: -34.604, lng: -58.38 },
    ],
    center: { lat: -34.606, lng: -58.3775 },
    area: 38.2,
    status: "regular",
    details: {
      ganado: 62,
      estado: "Necesita rotación",
      ultimaInspeccion: "2024-01-25",
      responsable: "Ana García",
    },
  },
  {
    id: "cultivo-1",
    name: "Lote Maíz A",
    type: "cultivo",
    coordinates: [
      { lat: -34.602, lng: -58.385 },
      { lat: -34.602, lng: -58.39 },
      { lat: -34.598, lng: -58.39 },
      { lat: -34.598, lng: -58.385 },
    ],
    center: { lat: -34.6, lng: -58.3875 },
    area: 52.3,
    status: "bueno",
    details: {
      cultivo: "Maíz",
      estado: "Floración",
      ultimaInspeccion: "2024-01-29",
      responsable: "Miguel Torres",
    },
  },
  {
    id: "cultivo-2",
    name: "Lote Soja B",
    type: "cultivo",
    coordinates: [
      { lat: -34.608, lng: -58.385 },
      { lat: -34.608, lng: -58.39 },
      { lat: -34.604, lng: -58.39 },
      { lat: -34.604, lng: -58.385 },
    ],
    center: { lat: -34.606, lng: -58.3875 },
    area: 41.7,
    status: "critico",
    details: {
      cultivo: "Soja",
      estado: "Estrés hídrico",
      ultimaInspeccion: "2024-01-30",
      responsable: "Luis Rodríguez",
    },
  },
]

export const mapMarkers: MapMarker[] = [
  {
    id: "tractor-1",
    name: "Tractor John Deere 6120M",
    type: "vehiculo",
    coordinates: { lat: -34.601, lng: -58.378 },
    status: "activo",
    details: vehicles[0],
    icon: Tractor,
  },
  {
    id: "sensor-1",
    name: "Sensor Humedad S-001",
    type: "sensor",
    coordinates: { lat: -34.6005, lng: -58.377 },
    status: "activo",
    details: { humidity: 68, temperature: 24, battery: 85 },
    icon: Droplets,
  },
  {
    id: "sensor-2",
    name: "Sensor Temperatura S-002",
    type: "sensor",
    coordinates: { lat: -34.605, lng: -58.386 },
    status: "alerta",
    details: { humidity: 45, temperature: 32, battery: 15 },
    icon: Thermometer,
  },
  {
    id: "corral-1",
    name: "Corral Principal",
    type: "infraestructura",
    coordinates: { lat: -34.603, lng: -58.382 },
    status: "activo",
    details: { capacidad: 200, ocupacion: 45, tipo: "Manejo" },
    icon: Home,
  },
  {
    id: "galpón-1",
    name: "Galpón de Herramientas",
    type: "infraestructura",
    coordinates: { lat: -34.604, lng: -58.381 },
    status: "activo",
    details: { tipo: "Almacenamiento", area: 150 },
    icon: Warehouse,
  },
  {
    id: "alerta-1",
    name: "Cerca Caída",
    type: "alerta",
    coordinates: { lat: -34.607, lng: -58.379 },
    status: "alerta",
    details: { tipo: "Infraestructura", prioridad: "Alta" },
    icon: AlertTriangle,
  },
  {
    id: "agua-1",
    name: "Bebedero Norte",
    type: "agua",
    coordinates: { lat: -34.6, lng: -58.3785 },
    status: "activo",
    details: { nivel: 85, flujo: "Normal" },
    icon: Waves,
  },
]

export const marketData = {
  insumos: [
    {
      id: "fertilizante-npk",
      name: "Fertilizante NPK 20-20-20",
      category: "Fertilizantes",
      currentPrice: 45.5,
      previousPrice: 43.2,
      change: 5.32,
      changeType: "increase" as const,
      unit: "por saco 50kg",
      supplier: "AgroInsumos SA",
      trend: [40, 42, 41, 43, 45, 46, 45.5],
      volume: 1250,
      lastUpdate: "hace 2h",
    },
    {
      id: "semilla-maiz",
      name: "Semilla Maíz Híbrido DK390",
      category: "Semillas",
      currentPrice: 12.3,
      previousPrice: 12.8,
      change: -3.91,
      changeType: "decrease" as const,
      unit: "por kg",
      supplier: "Semillas Premium",
      trend: [13, 12.8, 12.5, 12.3, 12.1, 12.4, 12.3],
      volume: 850,
      lastUpdate: "hace 1h",
    },
    {
      id: "herbicida-glifosato",
      name: "Herbicida Glifosato 48%",
      category: "Agroquímicos",
      currentPrice: 28.75,
      previousPrice: 29.1,
      change: -1.2,
      changeType: "decrease" as const,
      unit: "por litro",
      supplier: "QuímicaAgro",
      trend: [30, 29.5, 29.1, 28.8, 28.5, 28.9, 28.75],
      volume: 420,
      lastUpdate: "hace 30m",
    },
  ],
  productos: [
    {
      id: "maiz-grano",
      name: "Maíz Grano",
      category: "Granos",
      currentPrice: 185.5,
      previousPrice: 182.3,
      change: 1.75,
      changeType: "increase" as const,
      unit: "por tonelada",
      market: "Mercado de Rosario",
      trend: [180, 182, 184, 183, 185, 186, 185.5],
      volume: 2500,
      lastUpdate: "hace 15m",
    },
    {
      id: "soja-grano",
      name: "Soja Grano",
      category: "Granos",
      currentPrice: 320.8,
      previousPrice: 315.2,
      change: 1.78,
      changeType: "increase" as const,
      unit: "por tonelada",
      market: "Mercado de Buenos Aires",
      trend: [310, 315, 318, 320, 322, 319, 320.8],
      volume: 1800,
      lastUpdate: "hace 10m",
    },
    {
      id: "trigo",
      name: "Trigo Pan",
      category: "Granos",
      currentPrice: 195.4,
      previousPrice: 198.6,
      change: -1.61,
      changeType: "decrease" as const,
      unit: "por tonelada",
      market: "Mercado de Córdoba",
      trend: [200, 198, 196, 195, 194, 197, 195.4],
      volume: 950,
      lastUpdate: "hace 25m",
    },
  ],
  ganado: [
    {
      id: "novillo-gordo",
      name: "Novillo Gordo 400-450kg",
      category: "Bovinos",
      currentPrice: 2.85,
      previousPrice: 2.78,
      change: 2.52,
      changeType: "increase" as const,
      unit: "por kg vivo",
      market: "Mercado de Liniers",
      trend: [2.7, 2.75, 2.78, 2.8, 2.82, 2.84, 2.85],
      volume: 3200,
      lastUpdate: "hace 45m",
    },
    {
      id: "vaca-conserva",
      name: "Vaca Conserva",
      category: "Bovinos",
      currentPrice: 2.45,
      previousPrice: 2.42,
      change: 1.24,
      changeType: "increase" as const,
      unit: "por kg vivo",
      market: "Mercado de Liniers",
      trend: [2.4, 2.41, 2.42, 2.44, 2.43, 2.45, 2.45],
      volume: 1850,
      lastUpdate: "hace 45m",
    },
    {
      id: "ternero-destete",
      name: "Ternero Destete 180-200kg",
      category: "Bovinos",
      currentPrice: 3.2,
      previousPrice: 3.15,
      change: 1.59,
      changeType: "increase" as const,
      unit: "por kg vivo",
      market: "Mercado Regional",
      trend: [3.1, 3.12, 3.15, 3.18, 3.16, 3.19, 3.2],
      volume: 890,
      lastUpdate: "hace 1h",
    },
  ],
  maquinaria: [
    {
      id: "tractor-usado",
      name: "Tractor John Deere 6120M (2018)",
      category: "Tractores",
      currentPrice: 85000,
      previousPrice: 87500,
      change: -2.86,
      changeType: "decrease" as const,
      unit: "por unidad",
      supplier: "MaquiAgro SA",
      trend: [90000, 88000, 87500, 86000, 85500, 85200, 85000],
      volume: 12,
      lastUpdate: "hace 3h",
    },
    {
      id: "cosechadora-usada",
      name: "Cosechadora Case IH 8250 (2019)",
      category: "Cosechadoras",
      currentPrice: 180000,
      previousPrice: 175000,
      change: 2.86,
      changeType: "increase" as const,
      unit: "por unidad",
      supplier: "Implementos del Campo",
      trend: [170000, 172000, 175000, 178000, 179000, 181000, 180000],
      volume: 8,
      lastUpdate: "hace 2h",
    },
  ],
}

export const weatherStations: WeatherStation[] = [
  {
    id: "ws-1",
    name: "Estación Norte",
    coordinates: { lat: -34.599, lng: -58.378 },
    temperature: 24,
    humidity: 68,
    windSpeed: 12,
    rainfall: 2.5,
    soilMoisture: 45,
    lastUpdate: "hace 5m",
  },
  {
    id: "ws-2",
    name: "Estación Sur",
    coordinates: { lat: -34.607, lng: -58.387 },
    temperature: 26,
    humidity: 62,
    windSpeed: 8,
    rainfall: 1.8,
    soilMoisture: 38,
    lastUpdate: "hace 3m",
  },
]
