"use client"
import { useEffect, useRef, useState, type FormEvent } from "react"
import Link from "next/link"
import { useQuery, useQueryClient } from "@tanstack/react-query"
import { ArrowLeft, Pencil, X } from "lucide-react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import type { MapSector, SectorRecord } from "@/lib/mapa/types"
import { isParcel, livestockTypes, sectorState, waterLabel } from "@/lib/mapa/sector-state"
import { filterAnimals } from "@/lib/mapa/filters"
interface Detail {
  puedeEditar: boolean; totalRegistros: number; registros: SectorRecord[];
  animales: { id: string; caravanaVisual: string | null; otroId: string | null; especie: { nombre: string }; categoria: { nombre: string } | null }[];
  grupos: { id: string; nombre: string; especie: { nombre: string } }[];
  cultivos: { id: string; forraje: { nombre: string }; desde: string; hasta: string | null; superficieHa: number | null; version: number; notas: string | null }[];
  documentos: { id: string; titulo: string; mime: string; nombreArchivo: string }[];
  movimientos: { id: string; fecha: string; animal: { caravanaVisual: string | null } | null; origenSector: { nombre: string } | null; destinoSector: { nombre: string } | null }[];
  reservas: { id: string; nombre: string; stock: string; unidad: string }[];
  productos: { id: string; nombre: string }[]; existencias: { id: string; nombre: string; cantidad: number }[];
}
const select = "erp-select w-full"
const date = (s: string) => new Date(s).toLocaleDateString("es-AR", { timeZone: "America/Argentina/Buenos_Aires" })
const today = () => new Date().toLocaleDateString("en-CA", { timeZone: "America/Argentina/Buenos_Aires" })
const labels: Record<string, string> = { nota: "Nota", tarea: "Tarea", revision_agua: "Revisión de agua", descanso: "Descanso", labor: "Labor / cosecha", medicion: "Medición de pasto", pendiente: "Pendiente", completada: "Completada", registrado: "Registrado", disponible: "Agua disponible", sin_agua: "Sin agua", requiere_revision: "Requiere revisión", inicio: "Inicio", fin: "Fin" }
type Action = "record" | "move" | "group" | "crop" | "stock" | "document"
export function SectorPanel({ sector, fieldId, sectors, onBack, onEdit, onEditingChange }: { sector: MapSector; fieldId: string; sectors: MapSector[]; onBack: () => void; onEdit: () => void; onEditingChange: (editing: boolean) => void }) {
  const client = useQueryClient(), [tab, setTab] = useState("resumen"), [page, setPage] = useState(1)
  const [action, setAction] = useState<Action | null>(null), [animalSearch, setAnimalSearch] = useState("")
  const scroll = useRef<HTMLDivElement>(null), heading = useRef<HTMLHeadingElement>(null)
  useEffect(() => { if (scroll.current) scroll.current.scrollTop = 0 }, [action, tab])
  useEffect(() => { heading.current?.focus({ preventScroll: true }) }, [])
  const [saving, setSaving] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("")
  const [kind, setKind] = useState("nota"), [status, setStatus] = useState("registrado"), [text, setText] = useState("")
  const [key, setKey] = useState(() => crypto.randomUUID()), [selected, setSelected] = useState<string[]>([])
  const [species, setSpecies] = useState("todos"), [destination, setDestination] = useState(""), [group, setGroup] = useState("")
  const [forage, setForage] = useState(""), [hectares, setHectares] = useState(""), [sowing, setSowing] = useState(today)
  const [height, setHeight] = useState(""), [coverage, setCoverage] = useState("")
  const [cropEnd, setCropEnd] = useState(today), [file, setFile] = useState<File | null>(null), [fileTitle, setFileTitle] = useState("")
  const [product, setProduct] = useState(""), [stockType, setStockType] = useState("entrada"), [quantity, setQuantity] = useState(""), [stockReason, setStockReason] = useState("")
  useEffect(() => { onEditingChange(!!action || saving); return () => onEditingChange(false) }, [action, saving, onEditingChange])
  const query = useQuery<Detail>({ queryKey: ["sector-ficha", sector.id, page], queryFn: async ({ signal }) => {
    const r = await fetch(`/api/sectores/${sector.id}/ficha?page=${page}`, { signal }), b = await r.json(); if (!r.ok) throw Error(b.error); return b
  } })
  const catalog = useQuery<{ forrajes: { id: string; nombre: string }[] }>({ queryKey: ["campo-catalogos", fieldId], enabled: action === "crop", queryFn: async () => { const r = await fetch(`/api/campo/catalogos?establecimientoId=${fieldId}`); if (!r.ok) throw Error("No se pudo cargar el catálogo"); return r.json() } })
  const data = query.data, canEdit = data?.puedeEditar ?? false
  async function send(url: string, body: unknown, method = "POST") {
    setSaving(true); setError(""); setNotice("")
    try {
      const r = await fetch(url, { method, ...(body instanceof FormData ? { body } : { headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }) }), b = await r.json()
      if (!r.ok) throw Error(b.error ?? "No se pudo guardar")
      await Promise.all(["sector-ficha", "mapa", "sectores", "ganado-lista", "pastoreos-activos"].map(key => client.invalidateQueries({ queryKey: [key] })))
      setKey(crypto.randomUUID()); setAction(null); setSelected([]); setNotice("Guardado en el campo. La información está actualizada."); return true
    } catch (e) { setError(e instanceof Error ? e.message : "No se pudo guardar"); return false } finally { setSaving(false) }
  }
  function chooseKind(value: string) { setKind(value); setStatus(value === "tarea" ? "pendiente" : value === "revision_agua" ? "disponible" : value === "descanso" ? "inicio" : "registrado"); setKey(crypto.randomUUID()) }
  async function record(e: FormEvent) { e.preventDefault(); if (kind === "medicion") { if (await send(`/api/sectores/${sector.id}/mediciones`, { fecha: today(), alturaPastoCm: height, coberturaPct: coverage, observ: text })) { setHeight(""); setCoverage(""); setText("") }; return }; if (await send(`/api/sectores/${sector.id}/ficha`, { clave: key, tipo: kind, estado: status, detalle: text })) setText("") }
  const visibleAnimals = filterAnimals(data?.animales ?? [], species, animalSearch)
  function startAction(next: Action, nextTab: string) { setAction(next); setTab(nextTab); setError(""); setNotice(""); setSelected([]); setDestination(""); setGroup("") }
  function cancelAction() { setAction(null); setSelected([]); setError(""); setText(""); setHeight(""); setCoverage(""); setFile(null); setFileTitle(""); setQuantity(""); setStockReason(""); setHectares(""); setKey(crypto.randomUUID()) }
  const tabs = [["resumen", "Resumen"], ...(livestockTypes.has(sector.tipo) ? [["animales", "Ganado"]] : []), ["actividad", "Actividad"], ...(isParcel(sector.tipo) ? [["cultivos", "Cultivos"]] : []), ...(sector.tipo === "galpon" ? [["stock", "Existencias"]] : []), ...(canEdit ? [["documentos", "Archivos"]] : []) ]
  return <section aria-label={`Ficha de ${sector.nombre}`} className="flex h-full min-h-0 flex-col">
    <header className="shrink-0 space-y-3 border-b p-4">
      <div className="flex items-center justify-between gap-2"><Button size="sm" variant="ghost" className="-ml-2" disabled={saving || !!action} onClick={onBack}><ArrowLeft className="mr-1 h-4 w-4"/>Volver a lugares</Button>{canEdit && <Button size="icon" variant="ghost" aria-label="Editar límites del lugar" title="Editar límites" disabled={saving || !!action} onClick={onEdit}><Pencil className="h-4 w-4"/></Button>}</div>
      <div><h2 ref={heading} tabIndex={-1} className="text-lg font-semibold leading-tight focus:outline-none">{sector.nombre}</h2><p className="mt-1 text-sm text-muted-foreground">{sectorState(sector).label}{livestockTypes.has(sector.tipo) ? ` · ${sector.bovinos} bovinos · ${sector.ovinos} ovinos` : ""}</p></div>
      {canEdit && !action && <div className="flex flex-wrap gap-2">
        {livestockTypes.has(sector.tipo) && <Button size="sm" onClick={() => startAction("move", "animales")}>Mover animales</Button>}
        {sector.tipo === "galpon" && <Button size="sm" onClick={() => startAction("stock", "stock")}>Entrada / salida de stock</Button>}
        <Button size="sm" variant={livestockTypes.has(sector.tipo) || sector.tipo === "galpon" ? "outline" : "default"} onClick={() => startAction("record", "actividad")}>Registrar actividad</Button>
      </div>}
      {action && <div className="flex items-center justify-between gap-2 rounded-lg bg-muted p-2 text-sm"><span>{{record:"Registrar actividad",move:"Mover animales",group:"Ingresar un grupo",crop:"Registrar siembra",stock:"Movimiento de stock",document:"Adjuntar archivo"}[action]}</span><Button size="sm" variant="ghost" disabled={saving} onClick={cancelAction}><X className="mr-1 h-4 w-4"/>Cancelar</Button></div>}
    </header>
    <div ref={scroll} className="min-h-0 flex-1 space-y-4 overflow-y-auto overscroll-contain p-4" data-testid="sector-panel-scroll">
    <div className="flex flex-wrap gap-1 border-b pb-2" role="group" aria-label="Información del lugar">{tabs.map(([id, label]) => <Button key={id} variant={tab === id ? "secondary" : "ghost"} size="sm" aria-pressed={tab === id} disabled={saving || !!action} onClick={() => { setTab(id); setError(""); setNotice("") }}>{label}</Button>)}</div>
    {error && <p role="alert" className="erp-error">{error}</p>}{notice && <p role="status" className="erp-notice">{notice}</p>}
    {query.isPending ? <p role="status">Cargando ficha…</p> : query.isError ? <p role="alert">{query.error.message} <Button onClick={() => query.refetch()}>Reintentar</Button></p> : data && <>
      {tab === "resumen" && <div className="space-y-4 text-sm">
        <div className="grid grid-cols-2 gap-2">{livestockTypes.has(sector.tipo) && <button type="button" onClick={() => setTab("animales")} className="rounded-lg border p-3 text-left hover:bg-muted"><span className="block text-2xl font-semibold">{sector.bovinos + sector.ovinos}</span>Animales ubicados</button>}<button type="button" onClick={() => setTab("actividad")} className="rounded-lg border p-3 text-left hover:bg-muted"><span className="block text-2xl font-semibold">{sector.pendientes}</span>{sector.pendientes === 1 ? "Tarea pendiente" : "Tareas pendientes"}</button></div>
        {(isParcel(sector.tipo) || sector.tipo === "aguada" || sector.tieneAgua) && <div className="rounded-lg border p-3"><p className="font-medium">Agua · {waterLabel(sector.agua)}</p><p className="mt-1 text-xs text-muted-foreground">{sector.agua ? `Revisión: ${date(sector.agua.fecha)}` : "Todavía no se registró una revisión."}</p></div>}
        {(sector.areaMapaHa !== null || sector.superficieHa !== null) && <dl className="grid grid-cols-2 gap-3">{sector.areaMapaHa !== null && <div><dt className="text-muted-foreground">Dibujadas</dt><dd className="font-medium">{sector.areaMapaHa.toLocaleString("es-AR",{maximumFractionDigits:2})} ha</dd></div>}{sector.superficieHa !== null && <div><dt className="text-muted-foreground">Declaradas</dt><dd className="font-medium">{sector.superficieHa.toLocaleString("es-AR")} ha</dd></div>}</dl>}
        {sector.forrajes.length > 0 && <div><h3 className="mb-2 font-medium">Cultivos actuales</h3>{sector.forrajes.map(f => <p key={f.id}>{f.forraje.nombre} · {f.estado}{f.superficieHa != null ? ` · ${f.superficieHa} ha` : ""}</p>)}</div>}
        {sector.ultimaMedicion && <p>Última medición: {date(sector.ultimaMedicion.fecha)} · {sector.ultimaMedicion.alturaPastoCm ?? "—"} cm</p>}
        {sector.pastoreosIngreso.length > 0 && <details><summary className="cursor-pointer font-medium">Pastoreos declarados</summary>{sector.pastoreosIngreso.map(p => <p key={p.id} className="mt-2">{p.lote.nombre} · {p.lote.especie.nombre}</p>)}</details>}
        <details className="rounded-lg border p-3"><summary className="cursor-pointer font-medium">Descripción e instalaciones</summary><div className="mt-3 space-y-2 text-muted-foreground">{sector.descripcion && <p className="whitespace-pre-wrap">{sector.descripcion}</p>}{sector.capacidad !== null && <p>Capacidad declarada: {sector.capacidad} animales</p>}<p>{sector.tieneAgua ? "Instalación de agua registrada" : "Instalación de agua sin registrar"}</p>{sector.tieneSombra && <p>Sombra registrada</p>}</div></details>
      </div>}
      {tab === "actividad" && <div className="space-y-4">
        {canEdit && action === "record" && <form onSubmit={record} className="rounded-lg border p-4 space-y-3"><div className="grid gap-3 sm:grid-cols-2"><label className="erp-field"><span>Registrar</span><select className={select} value={kind} onChange={e => chooseKind(e.target.value)} disabled={saving}>{["nota", "tarea", "revision_agua", ...(isParcel(sector.tipo) ? ["descanso", "labor", "medicion"] : [])].map(t => <option key={t} value={t}>{labels[t]}</option>)}</select></label>{["revision_agua", "descanso"].includes(kind) && <label className="erp-field"><span>Resultado</span><select className={select} value={status} onChange={e => setStatus(e.target.value)} disabled={saving}>{(kind === "revision_agua" ? ["disponible", "sin_agua", "requiere_revision"] : ["inicio", "fin"]).map(t => <option key={t} value={t}>{labels[t]}</option>)}</select></label>}</div>{kind === "medicion" && <div className="grid gap-3 sm:grid-cols-2"><label className="erp-field"><span>Altura de pasto (cm)</span><Input required type="number" min="0" step="0.1" value={height} onChange={e => setHeight(e.target.value)}/></label><label className="erp-field"><span>Cobertura (%)</span><Input type="number" min="0" max="100" step="0.1" value={coverage} onChange={e => setCoverage(e.target.value)}/></label></div>}<label className="erp-field"><span>Detalle</span><Textarea required maxLength={3000} value={text} onChange={e => setText(e.target.value)} disabled={saving} placeholder="Ej. Revisar flotante del tanque antes de ingresar hacienda"/></label><Button disabled={saving || !text.trim()}>Guardar registro</Button><p className="text-xs text-muted-foreground">Se guarda con la fecha actual. El descanso es una decisión registrada por el encargado.</p></form>}
        {!action && <><h3 className="font-semibold">Historial del lugar</h3>{!data.registros.length && <p className="text-sm text-muted-foreground">Todavía no hay notas, revisiones ni tareas.</p>}{data.registros.map(r => <article key={r.id} className="rounded-lg border p-3 space-y-2"><div className="flex flex-wrap justify-between gap-2 text-xs text-muted-foreground"><span>{labels[r.tipo]} · {date(r.fecha)}</span><span>{labels[r.estado]}</span></div><p className="whitespace-pre-wrap text-sm">{r.detalle}</p>{r.tipo === "tarea" && r.estado === "pendiente" && canEdit && <Button size="sm" variant="outline" disabled={saving} onClick={() => send(`/api/sectores/${sector.id}/ficha`, { id: r.id, version: r.version }, "PATCH")}>Marcar completada</Button>}</article>)}
        {data.totalRegistros > 20 && <div className="flex items-center justify-between"><Button variant="outline" disabled={page === 1} onClick={() => setPage(v => v - 1)}>Anterior</Button><span>Página {page}</span><Button variant="outline" disabled={page * 20 >= data.totalRegistros} onClick={() => setPage(v => v + 1)}>Siguiente</Button></div>}
        {data.movimientos.length > 0 && <details className="rounded-lg border p-3"><summary className="cursor-pointer font-medium">Últimos movimientos de hacienda</summary>{data.movimientos.map(m => <p className="mt-3 text-sm" key={m.id}>{date(m.fecha)} · {m.animal?.caravanaVisual ?? "Animal"} · {m.origenSector?.nombre ?? "Sin ubicación anterior"} → {m.destinoSector?.nombre}</p>)}</details>}
</>}      </div>}
      {tab === "animales" && <div className="space-y-4">
        {action !== "group" && <>
          <div role="group" aria-label="Filtrar animales por especie" className="flex flex-wrap gap-1">
            {[["todos", "Todos"], ["bovino", "Bovinos"], ["ovino", "Ovinos"]].map(([value,label]) => <Button key={value} size="sm" variant={species === value ? "secondary" : "ghost"} aria-pressed={species === value} disabled={saving} onClick={() => { setSpecies(value); setSelected([]) }}>{label} ({filterAnimals(data.animales,value,"").length})</Button>)}
          </div>
          <Input aria-label="Buscar animal por caravana" placeholder="Buscar por caravana o identificación…" value={animalSearch} disabled={saving} onChange={e => { setAnimalSearch(e.target.value); setSelected([]) }}/>
          <p className="text-sm text-muted-foreground">{visibleAnimals.length} {visibleAnimals.length === 1 ? "animal" : "animales"}{animalSearch ? (visibleAnimals.length === 1 ? " encontrado" : " encontrados") : " en esta vista"}</p>
        </>}
        {canEdit && !action && <Button variant="outline" className="w-full" onClick={() => startAction("group", "animales")}>Ingresar un grupo a este lugar</Button>}
        {action === "move" && canEdit && <form className="space-y-3 rounded-lg border bg-muted/30 p-3" onSubmit={async e => { e.preventDefault(); await send("/api/mapa/movimientos", { animalIds: selected, origenSectorId: sector.id, destinoSectorId: destination }) }}>
          <p className="text-sm font-medium">{selected.length ? selected.length + (selected.length === 1 ? " seleccionado" : " seleccionados") : "Seleccioná los animales de la lista"}</p>
          <label className="erp-field"><span>Destino</span><select className={select} required value={destination} onChange={e => setDestination(e.target.value)} disabled={saving}><option value="">Elegir lugar en este campo</option>{sectors.filter(s => s.id !== sector.id && livestockTypes.has(s.tipo)).map(s => <option key={s.id} value={s.id}>{s.nombre}</option>)}</select></label>
          {selected.length > 0 && destination && <p className="text-sm">{selected.length} animales: {sector.nombre} → {sectors.find(s => s.id === destination)?.nombre}</p>}
          <Button className="w-full" disabled={saving || !selected.length || !destination}>{saving ? "Moviendo…" : "Confirmar movimiento"}</Button>
          <p className="text-xs text-muted-foreground">Actualiza la ubicación y conserva el historial. Si el grupo queda repartido, finaliza su pastoreo declarado.</p>
        </form>}
        {action !== "group" && <div className="space-y-1">
          {action === "move" && visibleAnimals.length > 0 && <label className="flex items-center gap-2 border-b py-2 text-sm"><input type="checkbox" disabled={saving} checked={visibleAnimals.every(a => selected.includes(a.id))} onChange={e => setSelected(e.target.checked ? visibleAnimals.map(a => a.id) : [])}/>Seleccionar los {visibleAnimals.length} de esta vista</label>}
          {visibleAnimals.map(a => <div key={a.id} className="flex items-center gap-2 rounded-lg border p-3 text-sm">{canEdit && action === "move" && <input type="checkbox" disabled={saving} aria-label={"Seleccionar " + (a.caravanaVisual ?? a.otroId ?? a.id)} checked={selected.includes(a.id)} onChange={e => setSelected(ids => e.target.checked ? [...ids, a.id] : ids.filter(id => id !== a.id))}/>}<div className="min-w-0"><Link className="break-words font-medium text-primary underline" href={"/ganado/"+a.id}>{a.caravanaVisual ?? a.otroId ?? "Sin identificación visual"}</Link><p className="text-xs text-muted-foreground">{a.especie.nombre} · {a.categoria?.nombre ?? "Sin categoría"}</p></div></div>)}
          {!visibleAnimals.length && <p className="rounded-lg border p-3 text-sm text-muted-foreground">No hay animales que coincidan. Probá otra especie o identificación.</p>}
        </div>}
        {canEdit && action === "group" && <form className="rounded-lg border p-3 space-y-3" onSubmit={async e => { e.preventDefault(); await send("/api/mapa/movimientos", { loteId: group, destinoSectorId: sector.id }) }}><label className="erp-field"><span>Grupo que ingresará a {sector.nombre}</span><select className={select} value={group} required onChange={e => setGroup(e.target.value)} disabled={saving}><option value="">Elegir grupo de animales</option>{data.grupos.map(g => <option key={g.id} value={g.id}>{g.nombre} · {g.especie.nombre}</option>)}</select></label><p className="text-xs text-muted-foreground">Mueve todos los animales activos del grupo a este lugar. En parcelas también inicia su pastoreo.</p><Button disabled={saving || !group}>Confirmar ingreso del grupo</Button></form>}
      </div>}
      {tab === "cultivos" && <div className="space-y-4"><p className="text-sm text-muted-foreground">Las campañas pertenecen a esta misma parcela. Cambiar de cultivo no crea otro potrero ni suma nuevamente sus hectáreas.</p>{canEdit && !action && <Button onClick={() => startAction("crop", "cultivos")}>Registrar siembra</Button>}{canEdit && action === "crop" && <form onSubmit={async e => { e.preventDefault(); if (await send("/api/campo/cultivos", { establecimientoId: fieldId, sectorId: sector.id, forrajeId: forage, desde: sowing, superficieHa: Number(hectares) })) setHectares("") }} className="rounded-lg border p-4 space-y-3"><label className="erp-field"><span>Cultivo / forraje</span><select className={select} required value={forage} onChange={e => setForage(e.target.value)}><option value="">Seleccionar</option>{catalog.data?.forrajes.map(f => <option key={f.id} value={f.id}>{f.nombre}</option>)}</select></label>{catalog.isError && <p role="alert">No se pudo cargar el catálogo. <button type="button" className="underline" onClick={() => catalog.refetch()}>Reintentar</button></p>}<div className="grid gap-3 sm:grid-cols-2"><label className="erp-field"><span>Fecha de siembra</span><Input type="date" required value={sowing} onChange={e => setSowing(e.target.value)}/></label><label className="erp-field"><span>Hectáreas sembradas</span><Input type="number" min="0.01" step="0.01" required value={hectares} onChange={e => setHectares(e.target.value)}/></label></div><Button disabled={saving || !forage}>Registrar siembra</Button></form>}
        {!action && <><h3 className="font-semibold">Campañas registradas</h3>{data.cultivos.map(c => <article key={c.id} className="rounded-lg border p-4 space-y-2"><p className="font-medium">{c.forraje.nombre} · {c.superficieHa ?? "—"} ha</p><p className="text-sm">{c.desde.slice(0, 10)} → {c.hasta?.slice(0, 10) ?? "En curso"}</p>{c.notas && <p className="text-sm">{c.notas}</p>}{!c.hasta && canEdit && <form className="flex flex-wrap gap-2" onSubmit={e => { e.preventDefault(); void send("/api/campo/cierre-cultivo", { establecimientoId: fieldId, cultivoId: c.id, version: c.version, hasta: cropEnd }) }}><Input aria-label={`Fecha de cierre de ${c.forraje.nombre}`} className="w-auto" type="date" value={cropEnd} onChange={e => setCropEnd(e.target.value)} required/><Button variant="outline" disabled={saving}>Finalizar campaña</Button></form>}</article>)}{!data.cultivos.length && <p className="text-sm text-muted-foreground">Sin campañas registradas.</p>}</>}</div>}
      {tab === "stock" && <div className="space-y-4">{!action && <><h3 className="font-semibold">Productos en este galpón</h3>{data.existencias.length ? data.existencias.map(p => <p key={p.id} className="flex justify-between rounded-lg border p-3 text-sm"><span>{p.nombre}</span><strong>{p.cantidad.toLocaleString("es-AR")}</strong></p>) : <p className="text-sm text-muted-foreground">Sin movimientos de productos asociados a este galpón. Las existencias antiguas sin ubicación siguen en Inventario.</p>}</>}{canEdit && action === "stock" && <form className="rounded-lg border p-4 space-y-3" onSubmit={async e => { e.preventDefault(); if (await send(`/api/sectores/${sector.id}/stock`, { clave: key, productoId: product, tipo: stockType, cantidad: Number(quantity), motivo: stockReason })) { setQuantity(""); setStockReason("") } }}><label className="erp-field"><span>Producto</span><select className={select} value={product} onChange={e => setProduct(e.target.value)} required><option value="">Seleccionar producto del catálogo</option>{data.productos.map(p => <option key={p.id} value={p.id}>{p.nombre}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label className="erp-field"><span>Movimiento</span><select className={select} value={stockType} onChange={e => setStockType(e.target.value)}><option value="entrada">Entrada</option><option value="salida">Salida</option></select></label><label className="erp-field"><span>Cantidad en unidades del producto</span><Input required type="number" min="0.01" step="0.01" value={quantity} onChange={e => setQuantity(e.target.value)}/></label></div><label className="erp-field"><span>Motivo</span><Input required maxLength={1000} value={stockReason} onChange={e => setStockReason(e.target.value)}/></label><Button disabled={saving || !product}>Registrar movimiento de stock</Button></form>}
        {!action && <><h3 className="font-semibold">Reservas de forraje</h3>{data.reservas.map(r => <p className="text-sm" key={r.id}>{r.nombre}: <strong>{r.stock} {r.unidad}</strong></p>)}{!data.reservas.length && <p className="text-sm text-muted-foreground">Sin reservas vinculadas a este depósito.</p>}<Button variant="outline" asChild><Link href={`/cultivos?vista=reservas&sectorId=${sector.id}`}>Administrar reservas de este galpón</Link></Button>
</>}      </div>}
      {tab === "documentos" && <div className="space-y-4">{canEdit && !action && <Button onClick={() => startAction("document", "documentos")}>Adjuntar foto o documento</Button>}{canEdit && action === "document" && <form className="rounded-lg border p-4 space-y-3" onSubmit={async e => { e.preventDefault(); if (!file) return; const form = new FormData(); form.set("archivo", file); form.set("metadata", JSON.stringify({ establecimientoId: fieldId, sectorId: sector.id, titulo: fileTitle || file.name, tipo: "otro", estado: "activo" })); if (await send("/api/administracion/documentos", form)) { setFile(null); setFileTitle("") } }}><label className="erp-field"><span>Descripción de la foto o documento</span><Input value={fileTitle} onChange={e => setFileTitle(e.target.value)} maxLength={180}/></label><label className="erp-field"><span>PDF, JPG o PNG · hasta 2 MB</span><Input type="file" accept="application/pdf,image/jpeg,image/png" onChange={e => setFile(e.target.files?.[0] ?? null)}/></label><Button disabled={saving || !file}>Adjuntar al lugar</Button></form>}{!action && <>{data.documentos.map(d => <a className="block rounded-lg border p-3 text-sm text-primary underline" key={d.id} href={`/api/documentos/${d.id}/archivo`}>{d.titulo} · {d.nombreArchivo}</a>)}{!data.documentos.length && <p className="text-sm text-muted-foreground">Todavía no hay archivos adjuntos a este lugar.</p>}</>}</div>}
    </>}
    </div>
  </section>
}
