"use client"
import { useState, type FormEvent } from "react"
import Link from "next/link"
import { useQuery, useQueryClient } from "@tanstack/react-query"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from "@/components/ui/dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import type { MapSector, SectorRecord } from "@/lib/mapa/types"
import { isParcel, livestockTypes, sectorState, waterLabel } from "@/lib/mapa/sector-state"
interface Detail {
  puedeEditar: boolean; totalRegistros: number; registros: SectorRecord[];
  animales: { id: string; caravanaVisual: string | null; otroId: string | null; especie: { nombre: string }; categoria: { nombre: string } | null }[];
  grupos: { id: string; nombre: string; especie: { nombre: string } }[];
  cultivos: { id: string; forraje: { nombre: string }; desde: string; hasta: string | null; superficieHa: number | null; version: number; notas: string | null }[];
  documentos: { id: string; titulo: string; mime: string; nombreArchivo: string }[];
  movimientos: { id: string; fecha: string; animal: { caravanaVisual: string | null } | null; origenSector: { nombre: string } | null; destinoSector: { nombre: string } | null }[];
  reservas: { id: string; nombre: string; stock: string; unidad: string }[];
  productos: { id: string; nombre: string }[]; existencias: { id: string; nombre: string; cantidad: number }[];
}
const select = "erp-select w-full"
const date = (s: string) => new Date(s).toLocaleDateString("es-AR", { timeZone: "America/Argentina/Buenos_Aires" })
const today = () => new Date().toLocaleDateString("en-CA", { timeZone: "America/Argentina/Buenos_Aires" })
const labels: Record<string, string> = { nota: "Nota", tarea: "Tarea", revision_agua: "Revisión de agua", descanso: "Descanso", labor: "Labor / cosecha", medicion: "Medición de pasto", pendiente: "Pendiente", completada: "Completada", registrado: "Registrado", disponible: "Agua disponible", sin_agua: "Sin agua", requiere_revision: "Requiere revisión", inicio: "Inicio", fin: "Fin" }
export function SectorPanel({ sector, fieldId, sectors, open, onOpenChange }: { sector: MapSector; fieldId: string; sectors: MapSector[]; open: boolean; onOpenChange: (open: boolean) => void }) {
  const client = useQueryClient(), [tab, setTab] = useState("actividad"), [page, setPage] = useState(1)
  const [saving, setSaving] = useState(false), [error, setError] = useState(""), [notice, setNotice] = useState("")
  const [kind, setKind] = useState("nota"), [status, setStatus] = useState("registrado"), [text, setText] = useState("")
  const [key, setKey] = useState(() => crypto.randomUUID()), [selected, setSelected] = useState<string[]>([])
  const [species, setSpecies] = useState("todos"), [destination, setDestination] = useState(""), [group, setGroup] = useState("")
  const [forage, setForage] = useState(""), [hectares, setHectares] = useState(""), [sowing, setSowing] = useState(today)
  const [height, setHeight] = useState(""), [coverage, setCoverage] = useState("")
  const [cropEnd, setCropEnd] = useState(today), [file, setFile] = useState<File | null>(null), [fileTitle, setFileTitle] = useState("")
  const [product, setProduct] = useState(""), [stockType, setStockType] = useState("entrada"), [quantity, setQuantity] = useState(""), [stockReason, setStockReason] = useState("")
  const query = useQuery<Detail>({ queryKey: ["sector-ficha", sector.id, page], enabled: open, queryFn: async ({ signal }) => {
    const r = await fetch(`/api/sectores/${sector.id}/ficha?page=${page}`, { signal }), b = await r.json(); if (!r.ok) throw Error(b.error); return b
  } })
  const catalog = useQuery<{ forrajes: { id: string; nombre: string }[] }>({ queryKey: ["campo-catalogos", fieldId], enabled: open && isParcel(sector.tipo), queryFn: async () => { const r = await fetch(`/api/campo/catalogos?establecimientoId=${fieldId}`); if (!r.ok) throw Error("No se pudo cargar el catálogo"); return r.json() } })
  const data = query.data, canEdit = data?.puedeEditar ?? false
  async function send(url: string, body: unknown, method = "POST") {
    setSaving(true); setError(""); setNotice("")
    try {
      const r = await fetch(url, { method, ...(body instanceof FormData ? { body } : { headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }) }), b = await r.json()
      if (!r.ok) throw Error(b.error ?? "No se pudo guardar")
      await Promise.all(["sector-ficha", "mapa", "sectores", "ganado-lista", "pastoreos-activos"].map(key => client.invalidateQueries({ queryKey: [key] })))
      setKey(crypto.randomUUID()); setNotice("Registro guardado. La información del campo está actualizada."); return true
    } catch (e) { setError(e instanceof Error ? e.message : "No se pudo guardar"); return false } finally { setSaving(false) }
  }
  function chooseKind(value: string) { setKind(value); setStatus(value === "tarea" ? "pendiente" : value === "revision_agua" ? "disponible" : value === "descanso" ? "inicio" : "registrado"); setKey(crypto.randomUUID()) }
  async function record(e: FormEvent) { e.preventDefault(); if (kind === "medicion") { if (await send(`/api/sectores/${sector.id}/mediciones`, { fecha: today(), alturaPastoCm: height, coberturaPct: coverage, observ: text })) { setHeight(""); setCoverage(""); setText("") }; return }; if (await send(`/api/sectores/${sector.id}/ficha`, { clave: key, tipo: kind, estado: status, detalle: text })) setText("") }
  const visibleAnimals = data?.animales.filter(a => species === "todos" || a.especie.nombre.toLowerCase() === species) ?? []
  const tabs = [ ...(livestockTypes.has(sector.tipo) ? [["animales", "Animales"]] : []), ["actividad", "Actividad y tareas"], ...(isParcel(sector.tipo) ? [["cultivos", "Cultivos"]] : []), ...(sector.tipo === "galpon" ? [["stock", "Existencias"]] : []), ...(canEdit ? [["documentos", "Fotos y documentos"]] : []) ]
  return <Dialog open={open} onOpenChange={v => { if (!saving) onOpenChange(v) }}><DialogContent className="max-h-[92dvh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>{sector.nombre}</DialogTitle><DialogDescription>{sectorState(sector).label}{livestockTypes.has(sector.tipo) ? ` · ${sector.bovinos} bovinos · ${sector.ovinos} ovinos` : ""}</DialogDescription></DialogHeader>
    <p className="text-sm text-muted-foreground">{sector.superficieHa !== null ? `${sector.superficieHa} ha declaradas · ` : ""}{sector.capacidad !== null ? `Capacidad declarada: ${sector.capacidad} animales · ` : ""}{sector.tieneAgua ? "Instalación de agua registrada" : "Instalación de agua sin registrar"}{sector.tieneSombra ? " · Sombra registrada" : ""}</p>
    <div className="flex flex-wrap gap-2 text-xs text-muted-foreground"><span>{waterLabel(sector.agua)}{sector.agua ? ` · ${date(sector.agua.fecha)}` : ""}</span><span>{sector.pendientes} tareas pendientes</span>{sector.ultimaMedicion && <span>Última medición: {date(sector.ultimaMedicion.fecha)} · {sector.ultimaMedicion.alturaPastoCm ?? "—"} cm</span>}</div>
    <div className="flex flex-wrap gap-1 border-b pb-2" role="group" aria-label="Información del lugar">{tabs.map(([id, label]) => <Button key={id} variant={tab === id ? "default" : "ghost"} size="sm" aria-pressed={tab === id} disabled={saving} onClick={() => { setTab(id); setError(""); setNotice("") }}>{label}</Button>)}</div>
    {error && <p role="alert" className="erp-error">{error}</p>}{notice && <p role="status" className="erp-notice">{notice}</p>}
    {query.isPending ? <p role="status">Cargando ficha…</p> : query.isError ? <p role="alert">{query.error.message} <Button onClick={() => query.refetch()}>Reintentar</Button></p> : data && <>
      {tab === "actividad" && <div className="space-y-4">
        {canEdit && <form onSubmit={record} className="rounded-lg border p-4 space-y-3"><div className="grid gap-3 sm:grid-cols-2"><label className="erp-field"><span>Registrar</span><select className={select} value={kind} onChange={e => chooseKind(e.target.value)} disabled={saving}>{["nota", "tarea", "revision_agua", ...(isParcel(sector.tipo) ? ["descanso", "labor", "medicion"] : [])].map(t => <option key={t} value={t}>{labels[t]}</option>)}</select></label>{["revision_agua", "descanso"].includes(kind) && <label className="erp-field"><span>Resultado</span><select className={select} value={status} onChange={e => setStatus(e.target.value)} disabled={saving}>{(kind === "revision_agua" ? ["disponible", "sin_agua", "requiere_revision"] : ["inicio", "fin"]).map(t => <option key={t} value={t}>{labels[t]}</option>)}</select></label>}</div>{kind === "medicion" && <div className="grid gap-3 sm:grid-cols-2"><label className="erp-field"><span>Altura de pasto (cm)</span><Input required type="number" min="0" step="0.1" value={height} onChange={e => setHeight(e.target.value)}/></label><label className="erp-field"><span>Cobertura (%)</span><Input type="number" min="0" max="100" step="0.1" value={coverage} onChange={e => setCoverage(e.target.value)}/></label></div>}<label className="erp-field"><span>Detalle</span><Textarea required maxLength={3000} value={text} onChange={e => setText(e.target.value)} disabled={saving} placeholder="Ej. Revisar flotante del tanque antes de ingresar hacienda"/></label><Button disabled={saving || !text.trim()}>Guardar registro</Button><p className="text-xs text-muted-foreground">Se guarda con la fecha actual. El descanso es una decisión registrada por el encargado.</p></form>}
        <h3 className="font-semibold">Historial del lugar</h3>{!data.registros.length && <p className="text-sm text-muted-foreground">Todavía no hay notas, revisiones ni tareas.</p>}{data.registros.map(r => <article key={r.id} className="rounded-lg border p-3 space-y-2"><div className="flex flex-wrap justify-between gap-2 text-xs text-muted-foreground"><span>{labels[r.tipo]} · {date(r.fecha)}</span><span>{labels[r.estado]}</span></div><p className="whitespace-pre-wrap text-sm">{r.detalle}</p>{r.tipo === "tarea" && r.estado === "pendiente" && canEdit && <Button size="sm" variant="outline" disabled={saving} onClick={() => send(`/api/sectores/${sector.id}/ficha`, { id: r.id, version: r.version }, "PATCH")}>Marcar completada</Button>}</article>)}
        {data.totalRegistros > 20 && <div className="flex items-center justify-between"><Button variant="outline" disabled={page === 1} onClick={() => setPage(v => v - 1)}>Anterior</Button><span>Página {page}</span><Button variant="outline" disabled={page * 20 >= data.totalRegistros} onClick={() => setPage(v => v + 1)}>Siguiente</Button></div>}
        {data.movimientos.length > 0 && <details className="rounded-lg border p-3"><summary className="cursor-pointer font-medium">Últimos movimientos de hacienda</summary>{data.movimientos.map(m => <p className="mt-3 text-sm" key={m.id}>{date(m.fecha)} · {m.animal?.caravanaVisual ?? "Animal"} · {m.origenSector?.nombre ?? "Sin ubicación anterior"} → {m.destinoSector?.nombre}</p>)}</details>}
      </div>}
      {tab === "animales" && <div className="space-y-4"><label className="erp-field"><span>Especie</span><select className={select} value={species} onChange={e => { setSpecies(e.target.value); setSelected([]) }}><option value="todos">Bovinos y ovinos</option><option value="bovino">Bovinos</option><option value="ovino">Ovinos</option></select></label><p className="text-sm">{visibleAnimals.length} animales ubicados en {sector.nombre}</p><div className="max-h-64 overflow-auto rounded-lg border">{visibleAnimals.map(a => <div key={a.id} className="flex items-center gap-3 border-b p-3 text-sm">{canEdit && <input type="checkbox" aria-label={`Seleccionar ${a.caravanaVisual ?? a.otroId ?? a.id}`} checked={selected.includes(a.id)} onChange={e => setSelected(ids => e.target.checked ? [...ids, a.id] : ids.filter(id => id !== a.id))}/>}<Link className="font-medium text-primary underline" href={`/ganado/${a.id}`}>{a.caravanaVisual ?? a.otroId ?? "Sin identificación visual"}</Link><span className="ml-auto text-muted-foreground">{a.especie.nombre} · {a.categoria?.nombre ?? "Sin categoría"}</span></div>)}</div>
        {canEdit && <><form className="rounded-lg border p-4 space-y-3" onSubmit={async e => { e.preventDefault(); if (await send("/api/mapa/movimientos", { animalIds: selected, origenSectorId: sector.id, destinoSectorId: destination })) setSelected([]) }}><label className="erp-field"><span>Mover {selected.length} animales seleccionados a</span><select className={select} required value={destination} onChange={e => setDestination(e.target.value)} disabled={saving}><option value="">Elegir destino en este campo</option>{sectors.filter(s => s.id !== sector.id && livestockTypes.has(s.tipo)).map(s => <option key={s.id} value={s.id}>{s.nombre}</option>)}</select></label><p className="text-xs text-muted-foreground">Se cierra la ubicación anterior y se registra la nueva. Si el grupo queda repartido, su pastoreo declarado se cierra.</p><Button disabled={saving || !selected.length || !destination}>Confirmar movimiento</Button></form>
        <form className="rounded-lg border p-4 space-y-3" onSubmit={async e => { e.preventDefault(); await send("/api/mapa/movimientos", { loteId: group, destinoSectorId: sector.id }) }}><label className="erp-field"><span>Traer un grupo completo a {sector.nombre}</span><select className={select} value={group} required onChange={e => setGroup(e.target.value)} disabled={saving}><option value="">Elegir grupo de animales</option>{data.grupos.map(g => <option key={g.id} value={g.id}>{g.nombre} · {g.especie.nombre}</option>)}</select></label><p className="text-xs text-muted-foreground">Mueve todos los animales activos del grupo a este lugar. En parcelas también inicia su pastoreo.</p><Button disabled={saving || !group} variant="outline">Confirmar ingreso del grupo</Button></form></>}
      </div>}
      {tab === "cultivos" && <div className="space-y-4"><p className="text-sm text-muted-foreground">Las campañas pertenecen a esta misma parcela. Cambiar de cultivo no crea otro potrero ni suma nuevamente sus hectáreas.</p>{canEdit && <form onSubmit={async e => { e.preventDefault(); if (await send("/api/campo/cultivos", { establecimientoId: fieldId, sectorId: sector.id, forrajeId: forage, desde: sowing, superficieHa: Number(hectares) })) setHectares("") }} className="rounded-lg border p-4 space-y-3"><label className="erp-field"><span>Cultivo / forraje</span><select className={select} required value={forage} onChange={e => setForage(e.target.value)}><option value="">Seleccionar</option>{catalog.data?.forrajes.map(f => <option key={f.id} value={f.id}>{f.nombre}</option>)}</select></label>{catalog.isError && <p role="alert">No se pudo cargar el catálogo. <button type="button" className="underline" onClick={() => catalog.refetch()}>Reintentar</button></p>}<div className="grid gap-3 sm:grid-cols-2"><label className="erp-field"><span>Fecha de siembra</span><Input type="date" required value={sowing} onChange={e => setSowing(e.target.value)}/></label><label className="erp-field"><span>Hectáreas sembradas</span><Input type="number" min="0.01" step="0.01" required value={hectares} onChange={e => setHectares(e.target.value)}/></label></div><Button disabled={saving || !forage}>Registrar siembra</Button></form>}
        <h3 className="font-semibold">Campañas registradas</h3>{data.cultivos.map(c => <article key={c.id} className="rounded-lg border p-4 space-y-2"><p className="font-medium">{c.forraje.nombre} · {c.superficieHa ?? "—"} ha</p><p className="text-sm">{c.desde.slice(0, 10)} → {c.hasta?.slice(0, 10) ?? "En curso"}</p>{c.notas && <p className="text-sm">{c.notas}</p>}{!c.hasta && canEdit && <form className="flex flex-wrap gap-2" onSubmit={e => { e.preventDefault(); void send("/api/campo/cierre-cultivo", { establecimientoId: fieldId, cultivoId: c.id, version: c.version, hasta: cropEnd }) }}><Input aria-label={`Fecha de cierre de ${c.forraje.nombre}`} className="w-auto" type="date" value={cropEnd} onChange={e => setCropEnd(e.target.value)} required/><Button variant="outline" disabled={saving}>Finalizar campaña</Button></form>}</article>)}{!data.cultivos.length && <p className="text-sm text-muted-foreground">Sin campañas registradas.</p>}</div>}
      {tab === "stock" && <div className="space-y-4"><h3 className="font-semibold">Productos en este galpón</h3>{data.existencias.length ? data.existencias.map(p => <p key={p.id} className="flex justify-between rounded-lg border p-3 text-sm"><span>{p.nombre}</span><strong>{p.cantidad.toLocaleString("es-AR")}</strong></p>) : <p className="text-sm text-muted-foreground">Sin movimientos de productos asociados a este galpón. Las existencias antiguas sin ubicación siguen en Inventario.</p>}{canEdit && <form className="rounded-lg border p-4 space-y-3" onSubmit={async e => { e.preventDefault(); if (await send(`/api/sectores/${sector.id}/stock`, { clave: key, productoId: product, tipo: stockType, cantidad: Number(quantity), motivo: stockReason })) { setQuantity(""); setStockReason("") } }}><label className="erp-field"><span>Producto</span><select className={select} value={product} onChange={e => setProduct(e.target.value)} required><option value="">Seleccionar producto del catálogo</option>{data.productos.map(p => <option key={p.id} value={p.id}>{p.nombre}</option>)}</select></label><div className="grid gap-3 sm:grid-cols-2"><label className="erp-field"><span>Movimiento</span><select className={select} value={stockType} onChange={e => setStockType(e.target.value)}><option value="entrada">Entrada</option><option value="salida">Salida</option></select></label><label className="erp-field"><span>Cantidad en unidades del producto</span><Input required type="number" min="0.01" step="0.01" value={quantity} onChange={e => setQuantity(e.target.value)}/></label></div><label className="erp-field"><span>Motivo</span><Input required maxLength={1000} value={stockReason} onChange={e => setStockReason(e.target.value)}/></label><Button disabled={saving || !product}>Registrar movimiento de stock</Button></form>}
        <h3 className="font-semibold">Reservas de forraje</h3>{data.reservas.map(r => <p className="text-sm" key={r.id}>{r.nombre}: <strong>{r.stock} {r.unidad}</strong></p>)}{!data.reservas.length && <p className="text-sm text-muted-foreground">Sin reservas vinculadas a este depósito.</p>}<Button variant="outline" asChild><Link href={`/cultivos?vista=reservas&sectorId=${sector.id}`}>Administrar reservas de este galpón</Link></Button>
      </div>}
      {tab === "documentos" && <div className="space-y-4">{canEdit && <form className="rounded-lg border p-4 space-y-3" onSubmit={async e => { e.preventDefault(); if (!file) return; const form = new FormData(); form.set("archivo", file); form.set("metadata", JSON.stringify({ establecimientoId: fieldId, sectorId: sector.id, titulo: fileTitle || file.name, tipo: "otro", estado: "activo" })); if (await send("/api/administracion/documentos", form)) { setFile(null); setFileTitle("") } }}><label className="erp-field"><span>Descripción de la foto o documento</span><Input value={fileTitle} onChange={e => setFileTitle(e.target.value)} maxLength={180}/></label><label className="erp-field"><span>PDF, JPG o PNG · hasta 2 MB</span><Input type="file" accept="application/pdf,image/jpeg,image/png" onChange={e => setFile(e.target.files?.[0] ?? null)}/></label><Button disabled={saving || !file}>Adjuntar al lugar</Button></form>}{data.documentos.map(d => <a className="block rounded-lg border p-3 text-sm text-primary underline" key={d.id} href={`/api/documentos/${d.id}/archivo`}>{d.titulo} · {d.nombreArchivo}</a>)}{!data.documentos.length && <p className="text-sm text-muted-foreground">Todavía no hay archivos adjuntos a este lugar.</p>}</div>}
    </>}
  </DialogContent></Dialog>
}
